### PR TITLE
Updating schemas for Catalogue, Dataset, and Distribution

### PR DESCRIPTION
**Pull request by flopezag**
Resolve some inconsistencies between the specification and the definition of the properties in the schema.json and correction of some typos.

### CODE REVIEW

**Comment by bobeal** [comment]
- Sometimes, it is `Catalogue`, other times it is `Catalog`. Should not it be `catalog` everywhere?
- Is it also an alignment with the new release of DCAT-AP (https://github.com/SEMICeu/DCAT-AP/releases/tag/3.0.0). Maybe a bit early for this since it is aligned with working draft of DCAT 3 ...

**Comment by flopezag** [comment]
There was only a description case in which it was used catalog. The DCAT-AP v2.0.1 use the nomenclature catalogue to make reference to this property. But the definition of the property "catalog" inside the Class Catalogue is defined as dcat:catalog.

In the current data model, we have adopted the name of the property equal to the  URI definition without prefix.

Regarding the migration to v3.0.0, this is something that is the roadmap to be done in the next iteration of this data model but not in the scope of this PR.

**Comment by bobeal** [comment]
> There was only a description case in which it was used catalog. The DCAT-AP v2.0.1 use the nomenclature catalogue to make reference to this property. But the definition of the property "catalog" inside the Class Catalogue is defined as dcat:catalog.
> 
> In the current data model, we have adopted the name of the property equal to the URI definition without prefix.

OK, just checked, `catalog` is American English and `catalogue` is British English. That explains why there is only `catalog` in DCAT, but `catalogue` in DCAT-AP ...

**Review by albertoabellagarcia — APPROVED** [review]
your're right

**Pull request merged**
